apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-sa-clusteradmin
  labels:
  {{- include "helmportainer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.saClusteradmin.serviceAccount.annotations | nindent 4 }}