apiVersion: v1
kind: Service
metadata:
  name: dssexternal
  labels:
  {{- include "helmdsmqtt.labels" . | nindent 4 }}
spec:
  type: {{ .Values.dssexternal.type }}
  externalName: {{ .Values.dssexternal.externalName }}