apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-config-pv
  labels:
    type: local
  {{- include "helmnodered.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /Users/insrsa/Organize/Personal/iHome/nodered/data
  storageClassName: generic