apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    io.kompose.service: nodered
  {{- include "helmnodered.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.nodered.replicas }}
  selector:
    matchLabels:
      io.kompose.service: nodered
    {{- include "helmnodered.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        io.kompose.network/nodered-default: "true"
        io.kompose.service: nodered
      {{- include "helmnodered.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: TZ
          value: {{ quote .Values.nodered.nodered.env.tz }}
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.nodered.nodered.image.repository }}:{{ .Values.nodered.nodered.image.tag
          | default .Chart.AppVersion }}
        name: nodered
        ports:
        - containerPort: 1880
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: nodered-config-pvc
      restartPolicy: Always
      volumes:
      - name: {{ .Release.Name }}-config-pvc
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-config-pvc