apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    io.kompose.service: nodered
  {{- include "helmnodered.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nodered.type }}
  selector:
    io.kompose.service: nodered
  {{- include "helmnodered.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.nodered.ports | toYaml | nindent 2 -}}