apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
  labels:
    io.kompose.service: {{ .Release.Name }}-data-pvc
  {{- include "helmmosquitto.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.dataPvc.storageRequest | quote }}
  selector:
    matchLabels:
      type: local
  storageClassName: {{ .Values.pvc.dataPvc.storageClass | quote }}
  volumeName: {{ .Release.Name }}-data-pv