apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    io.kompose.service: mosquitto
  {{- include "helmmosquitto.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (HEAD)
spec:
  type: {{ .Values.mosquitto.type }}
  selector:
    io.kompose.service: mosquitto
  {{- include "helmmosquitto.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.mosquitto.ports | toYaml | nindent 2 -}}