apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
  labels:
    type: local
  {{- include "helmmosquitto.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Mi
  hostPath:
    path: /Users/insrsa/Organize/Personal/iHome/mosquitto
  storageClassName: generic