apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    io.kompose.service: homeassistant
  {{- include "helmha.labels" . | nindent 4 }}
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.28.0 (HEAD)
spec:
  type: {{ .Values.homeassistant.type }}
  selector:
    io.kompose.service: homeassistant
  {{- include "helmha.selectorLabels" . | nindent 4 }}
    app.name: {{ .Release.Name }}
  ports:
	{{- .Values.homeassistant.ports | toYaml | nindent 2 -}}