apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-localtime-pvc
  labels:
    io.kompose.service: {{ .Release.Name }}-localtime-pvc
  {{- include "helmha.labels" . | nindent 4 }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.pvc.localtimePvc.storageRequest | quote }}
  selector:
    matchLabels:
      type: local
  storageClassName: {{ .Values.pvc.localtimePvc.storageClass | quote }}
  volumeName: {{ .Release.Name }}-localtime-pv